export const membershipCopy = {
  ar: {
    eyebrow: 'حسابك في MM CNC', title: 'ابدأ بعشر صور مجانية',
    description: '10 صور مختلفة لكل حساب. بعد ذلك، اشتراك سنوي بقيمة 30 دولارًا عبر شام كاش، يُفعّل بعد مراجعة الدفع.',
    signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب', email: 'البريد الإلكتروني', password: 'كلمة المرور',
    passwordHint: '8 أحرف على الأقل.', github: 'المتابعة بحساب GitHub', signOut: 'تسجيل الخروج',
    authUnavailable: 'تسجيل الحسابات غير متاح مؤقتًا. يرجى المحاولة لاحقًا بعد تفعيل خدمة الدخول.',
    forgotPassword: 'نسيت كلمة المرور؟', resetPassword: 'إرسال رابط الاستعادة', newPassword: 'كلمة المرور الجديدة', savePassword: 'حفظ كلمة المرور',
    verifyHint: 'سنرسل رابط تأكيد إلى بريدك. أكّد البريد قبل تسجيل الدخول واستخدام الرصيد.',
    signedIn: 'الحساب', refresh: 'تحديث الحالة', loading: 'جارٍ تحميل الحساب…', working: 'جارٍ التنفيذ…',
    used: 'الصور المستخدمة', remaining: 'صور مجانية متبقية', active: 'الاشتراك فعّال', trial: 'الرصيد المجاني',
    planRemaining: 'الصور المتاحة في اشتراكك', unlimited: 'غير محدود',
    privacy: 'نحفظ بريد حسابك وبصمة الصورة وعدد الاستخدامات ومرجع الدفع لإدارة الرصيد والاشتراك. تبقى الصورة نفسها على جهازك.',
    expired: 'الاشتراك منتهٍ', expires: 'صالح حتى', empty: 'اكتملت الصور المجانية',
    countedOnce: 'تصدير الصورة نفسها بصيغ متعددة يُحتسب مرة واحدة. يُحتسب الاستخدام عند التصدير.',
    subscription: 'الاشتراك السنوي', price: '30 دولارًا / سنة', paymentInstructions: 'حوّل 30 دولارًا إلى محفظة شام كاش الموضّحة، ثم أرسل رقم العملية للمراجعة.',
    calendarYear: 'يبدأ الاشتراك لمدة سنة تقويمية عند موافقة الإدارة. التجديد يضيف سنة إلى المدة المتبقية.',
    manualApproval: 'إرسال رقم العملية لا يفعّل الاشتراك فورًا. نراجعه بعد التأكد من وصول المبلغ إلى المحفظة.',
    qrAlt: 'رمز محفظة شام كاش لاستقبال الاشتراك', openQr: 'فتح بيانات محفظة شام كاش',
    sender: 'اسم المرسل في شام كاش (اختياري)', reference: 'رقم عملية التحويل', submitPayment: 'إرسال للمراجعة',
    pendingHint: 'طلبك قيد المراجعة. يمكنك تحديث الحالة بعد موافقة الإدارة.', history: 'طلبات الدفع',
    pending: 'قيد المراجعة', approved: 'مقبول', rejected: 'مرفوض', noHistory: 'لا توجد طلبات دفع بعد.',
    date: 'تاريخ الطلب', rejection: 'سبب الرفض', adminTitle: 'مراجعة المدفوعات', adminEmpty: 'لا توجد مدفوعات بانتظار المراجعة.',
    received: 'تحقّقت من وصول 30 دولارًا لهذه العملية إلى محفظة شام كاش.', approve: 'تأكيد الدفع وتفعيل سنة',
    reject: 'رفض الطلب', rejectReason: 'سبب رفض الطلب', adminHint: 'طابق رقم العملية واسم المرسل مع سجل المحفظة قبل الموافقة.',
    loadMore: 'عرض المزيد',
    errors: {
      config: 'خدمة الحساب غير متاحة حاليًا. يرجى المحاولة لاحقًا.',
      network: 'تعذّر التحقق من الحساب. افحص الاتصال وأعد المحاولة؛ لم نمنح إذن التصدير.',
      auth: 'تعذّر إكمال تسجيل الدخول. راجع البيانات وحاول مجددًا.',
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحين.',
      email_not_confirmed: 'أكّد بريدك الإلكتروني من رسالة التأكيد أولًا.',
      weak_password: 'استخدم كلمة مرور أقوى من 8 أحرف على الأقل.',
      user_already_exists: 'هذا الحساب موجود بالفعل. سجّل الدخول.',
      over_email_send_rate_limit: 'تعذّر إرسال رسالة أخرى الآن. انتظر قليلًا ثم حاول مجددًا.',
      signup_disabled: 'إنشاء الحسابات غير متاح حاليًا. حاول لاحقًا.',
      AUTH_REQUIRED: 'سجّل الدخول أولًا لتصدير الصور واستخدام رصيدك.',
      EMAIL_NOT_VERIFIED: 'أكّد بريدك الإلكتروني أولًا ثم سجّل الدخول مجددًا.',
      ADMIN_REQUIRED: 'لا تملك صلاحية إدارة المدفوعات.',
      PAYMENT_PENDING_EXISTS: 'لديك طلب دفع قيد المراجعة بالفعل.',
      REFERENCE_ALREADY_USED: 'رقم العملية مستخدم بالفعل. تحقّق من الرقم.',
      PAYMENT_ALREADY_REJECTED: 'رُفض هذا الطلب سابقًا. حدّث القائمة.',
      PAYMENT_ALREADY_APPROVED: 'تمت الموافقة على هذا الطلب سابقًا. حدّث القائمة.',
      quota: 'اكتملت الصور العشر المجانية. فعّل الاشتراك السنوي لتصدير صور جديدة.',
      hash: 'تعذّر التحقق من الصورة. أعد فتحها وحاول مجددًا.',
      accountChanged: 'تغيّر الحساب أثناء تجهيز الصورة. اضغط التصدير مجددًا باستخدام الحساب الحالي.',
      payment: 'تعذّر إرسال طلب الدفع. تحقّق من رقم العملية واتصالك ثم أعد المحاولة.',
      review: 'تعذّر حفظ القرار. حدّث قائمة المدفوعات وحاول مجددًا.',
      confirmation: 'أكد التحقق من وصول مبلغ 30 دولارًا قبل الموافقة.',
      reason: 'اكتب سببًا واضحًا للرفض (3 أحرف على الأقل).',
    },
    notices: {
      confirmEmail: 'تحقّق من بريدك الإلكتروني لتأكيد الحساب، ثم سجّل الدخول. قد تصل الرسالة إلى البريد غير المرغوب فيه.',
      paymentSent: 'أُرسل طلب الدفع للمراجعة. يبدأ اشتراكك بعد الموافقة.',
      paymentApproved: 'تم تأكيد الدفع وتفعيل الاشتراك.', paymentRejected: 'تم رفض الطلب وحفظ السبب.',
      passwordResetSent: 'إذا كان البريد مسجّلًا، ستصلك رسالة تحتوي رابط استعادة كلمة المرور.', passwordUpdated: 'تم تحديث كلمة المرور.',
    },
  },
  en: {
    eyebrow: 'Your MM CNC account', title: 'Start with ten free images',
    description: '10 different images per account. Then subscribe for $30 a year with Sham Cash, activated after payment review.',
    signIn: 'Sign in', signUp: 'Create account', email: 'Email address', password: 'Password',
    passwordHint: 'At least 8 characters.', github: 'Continue with GitHub', signOut: 'Sign out',
    authUnavailable: 'Account sign-in is temporarily unavailable. Please try again after the sign-in service is enabled.',
    forgotPassword: 'Forgot your password?', resetPassword: 'Send recovery link', newPassword: 'New password', savePassword: 'Save password',
    verifyHint: 'We will email you a confirmation link. Verify your email before signing in and using your allowance.',
    signedIn: 'Account', refresh: 'Refresh status', loading: 'Loading your account…', working: 'Working…',
    used: 'Images used', remaining: 'Free images remaining', active: 'Subscription active', trial: 'Free allowance',
    planRemaining: 'Images available with your plan', unlimited: 'Unlimited',
    privacy: 'We store your account email, image fingerprint, usage count and payment reference to manage your allowance and subscription. The image itself stays on your device.',
    expired: 'Subscription expired', expires: 'Valid until', empty: 'Free allowance used',
    countedOnce: 'Exporting the same image in multiple formats counts once. Usage is counted when you export.',
    subscription: 'Annual subscription', price: '$30 / year', paymentInstructions: 'Transfer $30 to the Sham Cash wallet shown, then submit your transaction reference for review.',
    calendarYear: 'Your subscription starts for one calendar year when approved. Renewals add a year to your remaining time.',
    manualApproval: 'Submitting a reference does not activate your subscription immediately. We review it after verifying receipt in the wallet.',
    qrAlt: 'Sham Cash wallet code for subscription payments', openQr: 'Open Sham Cash wallet details',
    sender: 'Sender name in Sham Cash (optional)', reference: 'Transaction reference', submitPayment: 'Submit for review',
    pendingHint: 'Your payment is being reviewed. Refresh the status after approval.', history: 'Payment requests',
    pending: 'Under review', approved: 'Approved', rejected: 'Rejected', noHistory: 'No payment requests yet.',
    date: 'Requested on', rejection: 'Rejection reason', adminTitle: 'Payment review', adminEmpty: 'No payments are waiting for review.',
    received: 'I verified that $30 for this transaction arrived in the Sham Cash wallet.', approve: 'Confirm payment and activate a year',
    reject: 'Reject request', rejectReason: 'Reason for rejection', adminHint: 'Match the transaction reference and sender with the wallet history before approving.',
    loadMore: 'Load more',
    errors: {
      config: 'The account service is currently unavailable. Please try again later.',
      network: 'We could not verify your account. Check your connection and retry; export has not been authorized.',
      auth: 'We could not complete sign-in. Check your details and try again.',
      invalid_credentials: 'The email address or password is incorrect.',
      email_not_confirmed: 'Confirm your email using the confirmation message first.',
      weak_password: 'Use a stronger password with at least 8 characters.',
      user_already_exists: 'This account already exists. Sign in instead.',
      over_email_send_rate_limit: 'Another email cannot be sent right now. Wait a little and retry.',
      signup_disabled: 'Account registration is currently unavailable. Please try later.',
      AUTH_REQUIRED: 'Sign in to export images and use your allowance.',
      EMAIL_NOT_VERIFIED: 'Verify your email first, then sign in again.',
      ADMIN_REQUIRED: 'You do not have permission to manage payments.',
      PAYMENT_PENDING_EXISTS: 'You already have a payment awaiting review.',
      REFERENCE_ALREADY_USED: 'This transaction reference has already been used. Check the reference.',
      PAYMENT_ALREADY_REJECTED: 'This request was already rejected. Refresh the list.',
      PAYMENT_ALREADY_APPROVED: 'This request was already approved. Refresh the list.',
      quota: 'Your ten free images have been used. Activate the annual subscription to export new images.',
      hash: 'We could not verify this image. Open it again and retry.',
      accountChanged: 'The account changed while the image was being prepared. Export again using the current account.',
      payment: 'We could not submit your payment. Check the transaction reference and your connection, then retry.',
      review: 'We could not save the decision. Refresh the payment list and retry.',
      confirmation: 'Confirm that you verified receipt of $30 before approving.',
      reason: 'Enter a clear rejection reason (at least 3 characters).',
    },
    notices: {
      confirmEmail: 'Check your email to confirm your account, then sign in. The message may arrive in your spam folder.',
      paymentSent: 'Payment submitted for review. Your subscription starts after approval.',
      paymentApproved: 'Payment confirmed and subscription activated.', paymentRejected: 'Request rejected and reason saved.',
      passwordResetSent: 'If this email is registered, you will receive a password recovery link.', passwordUpdated: 'Password updated.',
    },
  },
} as const;

export type MembershipError = keyof typeof membershipCopy.en.errors;
export type MembershipNotice = keyof typeof membershipCopy.en.notices;

export function membershipErrorCode(error: unknown, fallback: MembershipError): MembershipError {
  const value = error as { code?: string; message?: string } | null;
  if (value?.code && value.code in membershipCopy.en.errors) return value.code as MembershipError;
  const message = value?.message || '';
  const known = Object.keys(membershipCopy.en.errors).find(key => key === message || (key === key.toUpperCase() && message.includes(key)));
  return known as MembershipError || fallback;
}
